In [1]:
from google.colab import drive

# Mount Google Drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
import pandas as pd

file_path = '/content/drive/My Drive/modelpred.csv'
df = pd.read_csv(file_path)

df.head()

<ipython-input-2-a1f2f7fe5d56>:4: DtypeWarning: Columns (51,52,53) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)

,p_match,inns,bat,p_bat,team_bat,bowl,p_bowl,team_bowl,ball,ball_id,...,bat_out,wagonX,wagonY,wagonZone,line,length,shot,control,predscore,wprob
0,1001349,1,Aaron Finch,5334,Australia,Lasith Malinga,49758,Sri Lanka,1,0.01,...,True,208,178,3,ON_THE_STUMPS,SHORT_OF_A_GOOD_LENGTH,DEFENDED,0.0,-1,-1.0
1,1001349,1,Aaron Finch,5334,Australia,Lasith Malinga,49758,Sri Lanka,2,0.02,...,True,243,175,3,ON_THE_STUMPS,GOOD_LENGTH,DEFENDED,1.0,-1,-1.0
2,1001349,1,Aaron Finch,5334,Australia,Lasith Malinga,49758,Sri Lanka,3,0.03,...,True,189,242,4,ON_THE_STUMPS,SHORT_OF_A_GOOD_LENGTH,DEFENDED,0.0,-1,-1.0
3,1001351,1,Aaron Finch,5334,Australia,Lasith Malinga,49758,Sri Lanka,3,0.03,...,True,166,194,5,OUTSIDE_OFFSTUMP,SHORT_OF_A_GOOD_LENGTH,DEFENDED,1.0,-1,-1.0
4,1001351,1,Aaron Finch,5334,Australia,Lasith Malinga,49758,Sri Lanka,4,0.04,...,True,15,222,6,OUTSIDE_OFFSTUMP,GOOD_LENGTH,CUT_SHOT,1.0,-1,-1.0

#Selecting the required teams to avoid skewness

In [3]:
import pandas as pd


df = pd.read_csv(file_path)

# Define the set of teams
teams = {'Australia', 'Bangladesh', 'Afghanistan', 'India', 'England',
         'New Zealand', 'South Africa', 'Sri Lanka', 'Pakistan',
         'West Indies', 'Zimbabwe', 'Ireland', 'Scotland'}

# Filter the DataFrame based on the conditions
df = df[
    (df['inns'] == 1) &  # inns value should be 1
    (df['team_bat'].isin(teams)) &  # team_bat should be in the specified set
    (df['team_bowl'].isin(teams)) &  # team_bowl should be in the specified set
    (df['competition'] == 'T20I')  # competition should be 'T20I'
]

# Show the first few rows of the filtered DataFrame
df.head()

<ipython-input-3-a623c87c9845>:4: DtypeWarning: Columns (51,52,53) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)

,p_match,inns,bat,p_bat,team_bat,bowl,p_bowl,team_bowl,ball,ball_id,...,bat_out,wagonX,wagonY,wagonZone,line,length,shot,control,predscore,wprob
0,1001349,1,Aaron Finch,5334,Australia,Lasith Malinga,49758,Sri Lanka,1,0.01,...,True,208,178,3,ON_THE_STUMPS,SHORT_OF_A_GOOD_LENGTH,DEFENDED,0.0,-1,-1.0
1,1001349,1,Aaron Finch,5334,Australia,Lasith Malinga,49758,Sri Lanka,2,0.02,...,True,243,175,3,ON_THE_STUMPS,GOOD_LENGTH,DEFENDED,1.0,-1,-1.0
2,1001349,1,Aaron Finch,5334,Australia,Lasith Malinga,49758,Sri Lanka,3,0.03,...,True,189,242,4,ON_THE_STUMPS,SHORT_OF_A_GOOD_LENGTH,DEFENDED,0.0,-1,-1.0
3,1001351,1,Aaron Finch,5334,Australia,Lasith Malinga,49758,Sri Lanka,3,0.03,...,True,166,194,5,OUTSIDE_OFFSTUMP,SHORT_OF_A_GOOD_LENGTH,DEFENDED,1.0,-1,-1.0
4,1001351,1,Aaron Finch,5334,Australia,Lasith Malinga,49758,Sri Lanka,4,0.04,...,True,15,222,6,OUTSIDE_OFFSTUMP,GOOD_LENGTH,CUT_SHOT,1.0,-1,-1.0

#Finding Grounds which have atleast hold 5 matches

In [4]:
df['ground'].value_counts()[df['ground'].value_counts() > 600].sum()

70458

In [5]:
eligible_grounds = list(df['ground'].value_counts()[df['ground'].value_counts() > 600].index)
eligible_grounds

['Harare Sports Club',
 'Shere Bangla National Stadium, Mirpur',
 'Dubai International Cricket Stadium',
 'R Premadasa Stadium, Colombo',
 'Sharjah Cricket Stadium',
 'Gaddafi Stadium, Lahore',
 'Eden Park, Auckland',
 'Sydney Cricket Ground',
 'Zayed Cricket Stadium, Abu Dhabi',
 'Central Broward Regional Park Stadium Turf Ground, Lauderhill',
 'Kensington Oval, Bridgetown, Barbados',
 'Pallekele International Cricket Stadium',
 'Hagley Oval, Christchurch',
 'Melbourne Cricket Ground',
 'Daren Sammy National Cricket Stadium, Gros Islet, St Lucia',
 'Newlands, Cape Town',
 'Zahur Ahmed Chowdhury Stadium, Chattogram',
 'Bellerive Oval, Hobart',
 'Civil Service Cricket Club, Stormont, Belfast',
 'Warner Park, Basseterre, St Kitts',
 'Bay Oval, Mount Maunganui',
 'SuperSport Park, Centurion',
 'Grange Cricket Club Ground, Raeburn Place, Edinburgh',
 'Adelaide Oval',
 'Westpac Stadium, Wellington',
 'Eden Gardens, Kolkata',
 'Vidarbha Cricket Association Stadium, Jamtha, Nagpur',
 'Bready Cricket Club, Magheramason, Bready',
 'New Wanderers Stadium, Johannesburg',
 'The Rose Bowl, Southampton',
 'Old Trafford, Manchester',
 'Providence Stadium, Guyana',
 "National Cricket Stadium, St George's, Grenada",
 'Sabina Park, Kingston, Jamaica',
 'Seddon Park, Hamilton',
 'Perth Stadium',
 'Sophia Gardens, Cardiff',
 'Wankhede Stadium, Mumbai',
 'Kingsmead, Durban',
 'National Stadium, Karachi',
 'Brisbane Cricket Ground, Woolloongabba, Brisbane',
 'Sylhet International Cricket Stadium',
 'The Village, Malahide, Dublin',
 'Rajiv Gandhi International Cricket Stadium, Dehradun',
 'Punjab Cricket Association IS Bindra Stadium, Mohali, Chandigarh',
 'Greater Noida Sports Complex Ground, Greater Noida',
 'Narendra Modi Stadium, Ahmedabad',
 'McLean Park, Napier',
 'Rawalpindi Cricket Stadium',
 'Sheikh Zayed Stadium, Abu Dhabi',
 'Brian Lara Stadium, Tarouba, Trinidad',
 'Bharat Ratna Shri Atal Bihari Vajpayee Ekana Cricket Stadium, Lucknow',
 'Castle Avenue, Dublin',
 'Feroz Shah Kotla, Delhi']

In [6]:
df[df['ground'].isin(eligible_grounds)]

,p_match,inns,bat,p_bat,team_bat,bowl,p_bowl,team_bowl,ball,ball_id,...,bat_out,wagonX,wagonY,wagonZone,line,length,shot,control,predscore,wprob
0,1001349,1,Aaron Finch,5334,Australia,Lasith Malinga,49758,Sri Lanka,1,0.01,...,True,208,178,3,ON_THE_STUMPS,SHORT_OF_A_GOOD_LENGTH,DEFENDED,0.0,-1,-1.00
1,1001349,1,Aaron Finch,5334,Australia,Lasith Malinga,49758,Sri Lanka,2,0.02,...,True,243,175,3,ON_THE_STUMPS,GOOD_LENGTH,DEFENDED,1.0,-1,-1.00
2,1001349,1,Aaron Finch,5334,Australia,Lasith Malinga,49758,Sri Lanka,3,0.03,...,True,189,242,4,ON_THE_STUMPS,SHORT_OF_A_GOOD_LENGTH,DEFENDED,0.0,-1,-1.00
6,1001353,1,Aaron Finch,5334,Australia,Lasith Malinga,49758,Sri Lanka,1,0.01,...,True,143,197,6,ON_THE_STUMPS,SHORT_OF_A_GOOD_LENGTH,DEFENDED,1.0,-1,-1.00
7,1001353,1,Aaron Finch,5334,Australia,Lasith Malinga,49758,Sri Lanka,2,0.02,...,True,130,187,6,OUTSIDE_OFFSTUMP,GOOD_LENGTH,DEFENDED,1.0,-1,-1.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1760005,1420225,1,Shubman Gill,1070173,India,Wessly Madhevere,938959,Zimbabwe,3,12.03,...,True,228,315,4,ON_THE_STUMPS,FULL,ON_DRIVE,1.0,179,66.64
1760006,1420225,1,Ruturaj Gaikwad,1060380,India,Wessly Madhevere,938959,Zimbabwe,1,12.01,...,True,288,243,3,OUTSIDE_OFFSTUMP,GOOD_LENGTH,SLOG_SHOT,1.0,173,61.01
1760007,1420225,1,Ruturaj Gaikwad,1060380,India,Wessly Madhevere,938959,Zimbabwe,4,12.04,...,True,235,350,4,ON_THE_STUMPS,GOOD_LENGTH,ON_DRIVE,1.0,186,72.57
1760008,1420225,1,Ruturaj Gaikwad,1060380,India,Wessly Madhevere,938959,Zimbabwe,5,12.05,...,True,150,361,5,OUTSIDE_OFFSTUMP,FULL,ON_DRIVE,1.0,194,78.40
1760009,1420225,1,Ruturaj Gaikwad,1060380,India,Wessly Madhevere,938959,Zimbabwe,6,12.06,...,True,268,280,4,ON_THE_STUMPS,FULL,ON_DRIVE,1.0,196,79.70

In [8]:
df

,p_match,inns,bat,p_bat,team_bat,bowl,p_bowl,team_bowl,ball,ball_id,...,bat_out,wagonX,wagonY,wagonZone,line,length,shot,control,predscore,wprob
380659,722335,1,Reeza Hendricks,269280,South Africa,Sheldon Cottrell,495551,West Indies,1,0.01,...,True,249,33,1,DOWN_LEG,SHORT_OF_A_GOOD_LENGTH,PULL,1.0,-1,-1.00
380672,722335,1,Morne van Wyk,47711,South Africa,Sheldon Cottrell,495551,West Indies,2,0.02,...,True,0,0,0,ON_THE_STUMPS,GOOD_LENGTH,DEFENDED,0.0,-1,-1.00
380673,722335,1,Morne van Wyk,47711,South Africa,Sheldon Cottrell,495551,West Indies,3,0.03,...,True,350,132,2,DOWN_LEG,SHORT,PULL,1.0,-1,-1.00
380674,722335,1,Morne van Wyk,47711,South Africa,Sheldon Cottrell,495551,West Indies,4,0.04,...,True,119,153,7,OUTSIDE_OFFSTUMP,SHORT_OF_A_GOOD_LENGTH,CUT_SHOT,1.0,-1,-1.00
380675,722335,1,Morne van Wyk,47711,South Africa,Sheldon Cottrell,495551,West Indies,5,0.05,...,True,0,0,0,OUTSIDE_OFFSTUMP,GOOD_LENGTH,LEFT_ALONE,1.0,-1,-1.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1740422,1442989,1,Washington Sundar,719715,India,Maheesh Theekshana,1138316,Sri Lanka,2,19.02,...,True,308,252,3,ON_THE_STUMPS,GOOD_LENGTH,COVER_DRIVE,1.0,136,18.29
1740423,1442989,1,Washington Sundar,719715,India,Maheesh Theekshana,1138316,Sri Lanka,3,19.03,...,True,0,0,0,ON_THE_STUMPS,GOOD_LENGTH,SLOG_SHOT,0.0,135,17.66
1740424,1442989,1,Washington Sundar,719715,India,Maheesh Theekshana,1138316,Sri Lanka,4,19.04,...,True,15,290,6,OUTSIDE_OFFSTUMP,SHORT_OF_A_GOOD_LENGTH,PULL,0.0,140,21.01
1740425,1442989,1,Washington Sundar,719715,India,Maheesh Theekshana,1138316,Sri Lanka,5,19.05,...,True,0,0,0,ON_THE_STUMPS,FULL,REVERSE_SWEEP,0.0,138,19.61
1740429,1442989,1,Mohammed Siraj,940973,India,Maheesh Theekshana,1138316,Sri Lanka,6,19.06,...,True,0,0,0,WIDE_OUTSIDE_OFFSTUMP,SHORT_OF_A_GOOD_LENGTH,CUT_SHOT,0.0,137,18.95

In [9]:
# Assuming your data is in a DataFrame named 'df'
# Calculate 'balls_bowled' as the difference between 120 and 'inns_balls_rem'
df['balls_bowled'] = 120 - df['inns_balls_rem']

# Verify the result
print(df[['inns_balls_rem', 'balls_bowled']].head())

        inns_balls_rem  balls_bowled
380659             119             1
380672             118             2
380673             117             3
380674             116             4
380675             115             5

In [31]:
import pandas as pd

# Assuming your data is in a DataFrame named 'df'
# Sort the DataFrame by 'p_match' and 'ball_id' to ensure correct rolling calculation
df = df.sort_values(by=['p_match', 'ball_id'])

# Define a function to calculate rolling sum for Last5OversRuns
def calculate_last5oversruns(group):
    # Initialize 'Last5OversRuns' column as NaN for first 30 rows
    group['Last5OversRuns'] = group['score'].rolling(window=30).sum()
    return group

# Apply the function grouped by 'p_match'
df = df.groupby('p_match').apply(calculate_last5oversruns)

# Reset the index to avoid index issues after groupby
df = df.reset_index(drop=True)

# Verify the result
print(df[['p_match', 'ball_id', 'balls_bowled', 'score', 'Last5OversRuns']].head(50))

    p_match  ball_id  balls_bowled  score  Last5OversRuns
0    722335     0.01             1      1             NaN
1    722335     0.02             2      0             NaN
2    722335     0.03             3      6             NaN
3    722335     0.04             4      0             NaN
4    722335     0.05             5      0             NaN
5    722335     0.06             6      0             NaN
6    722335     1.01             7      0             NaN
7    722335     1.02             8      2             NaN
8    722335     1.03             9      0             NaN
9    722335     1.04            10      0             NaN
10   722335     1.05            11      0             NaN
11   722335     1.06            12      0             NaN
12   722335     2.01            13      0             NaN
13   722335     2.02            14      4             NaN
14   722335     2.03            15      1             NaN
15   722335     2.04            16      3             NaN
16   722335     2.05            17      4             NaN
17   722335     2.06            18      1             NaN
18   722335     3.01            19      0             NaN
19   722335     3.02            20      0             NaN
20   722335     3.03            21      1             NaN
21   722335     3.04            22      1             NaN
22   722335     3.05            23      1             NaN
23   722335     3.06            24      1             NaN
24   722335     4.01            25      4             NaN
25   722335     4.02            26      0             NaN
26   722335     4.03            27      0             NaN
27   722335     4.04            27      1             NaN
28   722335     4.05            28      2             NaN
29   722335     4.06            29      0            33.0
30   722335     4.07            30      0            32.0
31   722335     5.01            31      0            32.0
32   722335     5.02            32      0            26.0
33   722335     5.03            33      0            26.0
34   722335     5.04            34      1            27.0
35   722335     5.05            35      1            28.0
36   722335     5.06            36      0            28.0
37   722335     6.01            37      0            26.0
38   722335     6.02            38      0            26.0
39   722335     6.03            39      1            27.0
40   722335     6.04            40      1            28.0
41   722335     6.05            41      1            29.0
42   722335     6.06            42      1            30.0
43   722335     7.01            43      1            27.0
44   722335     7.02            44      4            30.0
45   722335     7.03            45      0            27.0
46   722335     7.04            46      4            27.0
47   722335     7.05            47      0            26.0
48   722335     7.06            48      4            30.0
49   722335     8.01            49      0            30.0

In [32]:
df[['balls_bowled', 'inns_wkts' , 'inns_runs', 'Last5OversRuns']].head(50)

    balls_bowled  inns_wkts  inns_runs  Last5OversRuns
0              1          0          1             NaN
1              2          0          1             NaN
2              3          0          7             NaN
3              4          0          7             NaN
4              5          0          7             NaN
5              6          0          7             NaN
6              7          0          7             NaN
7              8          0          9             NaN
8              9          0          9             NaN
9             10          0          9             NaN
10            11          0          9             NaN
11            12          0          9             NaN
12            13          0          9             NaN
13            14          0         13             NaN
14            15          0         14             NaN
15            16          0         17             NaN
16            17          0         21             NaN
17            18          0         22             NaN
18            19          0         22             NaN
19            20          0         22             NaN
20            21          0         23             NaN
21            22          0         24             NaN
22            23          0         25             NaN
23            24          0         26             NaN
24            25          0         30             NaN
25            26          1         30             NaN
26            27          1         30             NaN
27            27          1         31             NaN
28            28          1         33             NaN
29            29          1         33            33.0
30            30          1         33            32.0
31            31          2         33            32.0
32            32          2         33            26.0
33            33          2         33            26.0
34            34          2         34            27.0
35            35          2         35            28.0
36            36          2         35            28.0
37            37          2         35            26.0
38            38          2         35            26.0
39            39          2         36            27.0
40            40          2         37            28.0
41            41          2         38            29.0
42            42          2         39            30.0
43            43          2         40            27.0
44            44          2         44            30.0
45            45          2         44            27.0
46            46          2         48            27.0
47            47          2         48            26.0
48            48          2         52            30.0
49            49          2         52            30.0

#Finding Total Innings Runs Per p_match (match)

In [33]:
# Group by 'p_match' and sum the 'score', then rename the 'score' column
grouped_df = df.groupby('p_match').sum()['score'].reset_index().rename(columns={'score': 'total_score'})

# Merge it with the original DataFrame
merged_df = df.merge(grouped_df, on='p_match')

# Display the merged DataFrame
print(merged_df.head())

   p_match  inns              bat   p_bat      team_bat              bowl  \
0   722335     1  Reeza Hendricks  269280  South Africa  Sheldon Cottrell
1   722335     1    Morne van Wyk   47711  South Africa  Sheldon Cottrell
2   722335     1    Morne van Wyk   47711  South Africa  Sheldon Cottrell
3   722335     1    Morne van Wyk   47711  South Africa  Sheldon Cottrell
4   722335     1    Morne van Wyk   47711  South Africa  Sheldon Cottrell

   p_bowl    team_bowl  ball  ball_id  ...              line  \
0  495551  West Indies     1     0.01  ...          DOWN_LEG
1  495551  West Indies     2     0.02  ...     ON_THE_STUMPS
2  495551  West Indies     3     0.03  ...          DOWN_LEG
3  495551  West Indies     4     0.04  ...  OUTSIDE_OFFSTUMP
4  495551  West Indies     5     0.05  ...  OUTSIDE_OFFSTUMP

                   length        shot control  predscore  wprob  balls_bowled  \
0  SHORT_OF_A_GOOD_LENGTH        PULL     1.0         -1   -1.0             1
1             GOOD_LENGTH    DEFENDED     0.0         -1   -1.0             2
2                   SHORT        PULL     1.0         -1   -1.0             3
3  SHORT_OF_A_GOOD_LENGTH    CUT_SHOT     1.0         -1   -1.0             4
4             GOOD_LENGTH  LEFT_ALONE     1.0         -1   -1.0             5

   total_score_x  Last5OversRuns  total_score_y
0            165             NaN            165
1            165             NaN            165
2            165             NaN            165
3            165             NaN            165
4            165             NaN            165

[5 rows x 61 columns]

In [34]:
df = merged_df
df

,p_match,inns,bat,p_bat,team_bat,bowl,p_bowl,team_bowl,ball,ball_id,...,line,length,shot,control,predscore,wprob,balls_bowled,total_score_x,Last5OversRuns,total_score_y
0,722335,1,Reeza Hendricks,269280,South Africa,Sheldon Cottrell,495551,West Indies,1,0.01,...,DOWN_LEG,SHORT_OF_A_GOOD_LENGTH,PULL,1.0,-1,-1.00,1,165,NaN,165
1,722335,1,Morne van Wyk,47711,South Africa,Sheldon Cottrell,495551,West Indies,2,0.02,...,ON_THE_STUMPS,GOOD_LENGTH,DEFENDED,0.0,-1,-1.00,2,165,NaN,165
2,722335,1,Morne van Wyk,47711,South Africa,Sheldon Cottrell,495551,West Indies,3,0.03,...,DOWN_LEG,SHORT,PULL,1.0,-1,-1.00,3,165,NaN,165
3,722335,1,Morne van Wyk,47711,South Africa,Sheldon Cottrell,495551,West Indies,4,0.04,...,OUTSIDE_OFFSTUMP,SHORT_OF_A_GOOD_LENGTH,CUT_SHOT,1.0,-1,-1.00,4,165,NaN,165
4,722335,1,Morne van Wyk,47711,South Africa,Sheldon Cottrell,495551,West Indies,5,0.05,...,OUTSIDE_OFFSTUMP,GOOD_LENGTH,LEFT_ALONE,1.0,-1,-1.00,5,165,NaN,165
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
86472,1442989,1,Washington Sundar,719715,India,Maheesh Theekshana,1138316,Sri Lanka,2,19.02,...,ON_THE_STUMPS,GOOD_LENGTH,COVER_DRIVE,1.0,136,18.29,116,137,30.0,137
86473,1442989,1,Washington Sundar,719715,India,Maheesh Theekshana,1138316,Sri Lanka,3,19.03,...,ON_THE_STUMPS,GOOD_LENGTH,SLOG_SHOT,0.0,135,17.66,117,137,30.0,137
86474,1442989,1,Washington Sundar,719715,India,Maheesh Theekshana,1138316,Sri Lanka,4,19.04,...,OUTSIDE_OFFSTUMP,SHORT_OF_A_GOOD_LENGTH,PULL,0.0,140,21.01,118,137,35.0,137
86475,1442989,1,Washington Sundar,719715,India,Maheesh Theekshana,1138316,Sri Lanka,5,19.05,...,ON_THE_STUMPS,FULL,REVERSE_SWEEP,0.0,138,19.61,119,137,35.0,137
86476,1442989,1,Mohammed Siraj,940973,India,Maheesh Theekshana,1138316,Sri Lanka,6,19.06,...,WIDE_OUTSIDE_OFFSTUMP,SHORT_OF_A_GOOD_LENGTH,CUT_SHOT,0.0,137,18.95,120,137,35.0,137

#Checking Basic Stats

In [36]:
df[['balls_bowled', 'inns_wkts' , 'inns_runs', 'total_score_x', 'Last5OversRuns']].head(50)

    balls_bowled  inns_wkts  inns_runs  total_score_x  Last5OversRuns
0              1          0          1            165             NaN
1              2          0          1            165             NaN
2              3          0          7            165             NaN
3              4          0          7            165             NaN
4              5          0          7            165             NaN
5              6          0          7            165             NaN
6              7          0          7            165             NaN
7              8          0          9            165             NaN
8              9          0          9            165             NaN
9             10          0          9            165             NaN
10            11          0          9            165             NaN
11            12          0          9            165             NaN
12            13          0          9            165             NaN
13            14          0         13            165             NaN
14            15          0         14            165             NaN
15            16          0         17            165             NaN
16            17          0         21            165             NaN
17            18          0         22            165             NaN
18            19          0         22            165             NaN
19            20          0         22            165             NaN
20            21          0         23            165             NaN
21            22          0         24            165             NaN
22            23          0         25            165             NaN
23            24          0         26            165             NaN
24            25          0         30            165             NaN
25            26          1         30            165             NaN
26            27          1         30            165             NaN
27            27          1         31            165             NaN
28            28          1         33            165             NaN
29            29          1         33            165            33.0
30            30          1         33            165            32.0
31            31          2         33            165            32.0
32            32          2         33            165            26.0
33            33          2         33            165            26.0
34            34          2         34            165            27.0
35            35          2         35            165            28.0
36            36          2         35            165            28.0
37            37          2         35            165            26.0
38            38          2         35            165            26.0
39            39          2         36            165            27.0
40            40          2         37            165            28.0
41            41          2         38            165            29.0
42            42          2         39            165            30.0
43            43          2         40            165            27.0
44            44          2         44            165            30.0
45            45          2         44            165            27.0
46            46          2         48            165            27.0
47            47          2         48            165            26.0
48            48          2         52            165            30.0
49            49          2         52            165            30.0

In [44]:
df.rename(columns={'total_score_x': 'total_score'}, inplace=True)

#Final Data Frame

In [45]:
df_final = df[['team_bat', 'team_bowl', 'ground', 'balls_bowled', 'inns_wkts' , 'inns_runs', 'Last5OversRuns', 'total_score' ]]
df_final

,team_bat,team_bowl,ground,balls_bowled,inns_wkts,inns_runs,Last5OversRuns,total_score
0,South Africa,West Indies,"Newlands, Cape Town",1,0,1,NaN,165
1,South Africa,West Indies,"Newlands, Cape Town",2,0,1,NaN,165
2,South Africa,West Indies,"Newlands, Cape Town",3,0,7,NaN,165
3,South Africa,West Indies,"Newlands, Cape Town",4,0,7,NaN,165
4,South Africa,West Indies,"Newlands, Cape Town",5,0,7,NaN,165
...,...,...,...,...,...,...,...,...
86472,India,Sri Lanka,Pallekele International Cricket Stadium,116,7,131,30.0,137
86473,India,Sri Lanka,Pallekele International Cricket Stadium,117,7,131,30.0,137
86474,India,Sri Lanka,Pallekele International Cricket Stadium,118,7,137,35.0,137
86475,India,Sri Lanka,Pallekele International Cricket Stadium,119,8,137,35.0,137
86476,India,Sri Lanka,Pallekele International Cricket Stadium,120,9,137,35.0,137

In [46]:
df_final.isnull().sum(  )

team_bat              0
team_bowl             0
ground                0
balls_bowled          0
inns_wkts             0
inns_runs             0
Last5OversRuns    20654
total_score           0
dtype: int64

#Training

In [47]:
X = df_final.drop(columns=['total_score'])
y = df_final['total_score']

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=1)

In [48]:
X_train

,team_bat,team_bowl,ground,balls_bowled,inns_wkts,inns_runs,Last5OversRuns
6760,New Zealand,India,"Vidarbha Cricket Association Stadium, Jamtha, ...",71,4,63,28.0
29065,Afghanistan,Ireland,"Rajiv Gandhi International Cricket Stadium, De...",62,3,89,26.0
48673,Bangladesh,Australia,"Shere Bangla National Stadium, Mirpur",120,8,122,19.0
62820,Afghanistan,Zimbabwe,Harare Sports Club,105,7,105,20.0
66574,Zimbabwe,Bangladesh,Harare Sports Club,55,5,55,20.0
...,...,...,...,...,...,...,...
21440,Sri Lanka,Bangladesh,"R Premadasa Stadium, Colombo",16,1,21,NaN
73349,South Africa,Australia,"Kingsmead, Durban",39,2,53,43.0
50057,Ireland,Zimbabwe,"Bready Cricket Club, Magheramason, Bready",71,1,99,32.0
5192,West Indies,Sri Lanka,"R Premadasa Stadium, Colombo",98,4,137,41.0
77708,India,Australia,Shaheed Veer Narayan Singh International Stadi...,25,0,29,NaN

In [49]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestRegressor
from xgboost import XGBRegressor
from sklearn.metrics import r2_score, mean_absolute_error

In [50]:
trf = ColumnTransformer([
    ('trf',OneHotEncoder(drop='first'),['team_bat','team_bowl','ground'])
]
,remainder='passthrough')

pipe = Pipeline(steps=[
    ('step1', trf),
    ('step2', StandardScaler(with_mean=False)),  # Set with_mean=False here
    ('step3', XGBRegressor(n_estimators=1000, learning_rate=0.2, max_depth=12, random_state=1))
])

# Fitting the pipeline with training data
pipe.fit(X_train, y_train)

# Predicting the test data
y_pred = pipe.predict(X_test)

# Calculating the R^2 score
print(r2_score(y_test, y_pred))

# Calculating the Mean Absolute Error (MAE)
print(mean_absolute_error(y_test, y_pred))

0.9676980972290039
2.8773344756275496

In [51]:
import pickle

In [53]:
pickle.dump(pipe,open('pipe.pkl','wb'))